// ============================================================
//  FANTASYTRADER — price scraper (Supabase Edge Function)
//
//  Covers the ENTIRE 5,000-symbol draft universe, not a hand-picked
//  handful. The old version had 30 tickers hardcoded, which is why
//  most of the draft board showed "no price": nothing ever wrote a
//  row for those symbols, so the browser had to beg Yahoo for each
//  one individually and got rate-limited.
//
//  Resumable by design. One invocation works until its time budget
//  runs out, then reports where to pick up. Call it on a schedule
//  and it walks the whole universe.
//
//    /scrape-prices                  -> refresh whatever is stalest
//    /scrape-prices?mode=missing     -> only symbols with no row yet
//    /scrape-prices?offset=0&limit=800
//
//  DEPLOY: paste as the function's index.ts, Deploy.
//  SCHEDULE: every 5 minutes is plenty.
// ============================================================
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const SYMBOLS: string[] = (
  "AAPL NVDA MSFT GOOGL AMZN META BRK.B TSM AVGO TSLA LLY JPM WMT V SPY VOO MA IVV ORCL XOM VTI COST NFLX JNJ HD PG BAC LVMUY ABBV QQQ ASML NVO SAP UNH KO CVX CRM AMD TMUS MRK WFC NSRGY CSCO ADBE AZN NVS TM ACN AXP MCD PEP GE LIN BABA TMO ABT MS QCOM NOW IBM TXN INTU DIS VZ ISRG DHR GS BX HSBC RY PM CAT SIEGY CMCSA T BLK SPGI RTX AMAT UBER AMGN HDB UL NEE PGR UNP ARM SONY PDD PFE SYK SNY SCHW C LOW BKNG HON VEA INTC BSX TD TJX BA ETN GEV VUG MU ANET ADP VRTX DE COP VTV BND AGG PANW GILD MDT LRCX ADI CB KKR IBN UBS NKE BYDDY BUD LMT ABB PLD MMC SBUX MELI FI IWF KLAC PLTR APP SHOP BMY HCA ICE UPS SO AMT DELL SPOT CI ELV MCO BN MO MDLZ IEMG IJH ABNB GSK BAM WM TT CTAS DUK EQIX SHW SCCO VIG VWO SNPS CME APO CMG PH CEG WELL IJR GLD CDNS CRWD MRVL INFY MSI MCK REGN ZTS USB PNC AON AJG BMO CL GD TDG MMM ITW VXUS VO FTNT DASH CVS COF COIN PYPL BNS MAR NOC CP EOG ECL XLK EPD SE ORLY CSX CNI FDX EMR RSG WMB APD FCX IWM SCHD WDAY NTES TFC BK AFL NU RCL TGT DEO CARR KMI ET SPG NEM VYM RSP IWD VB BNDX NXPI COR MET TRV ARES AZO HLT GM NSC PCAR ROP JCI SLB OKE AEP SRE DLR AEM EFA IBIT SNOW TEAM PAYX JD CHTR BDX ALNY AIG ALL MFC ROST MNST AXON CMI URI GWW PSX MPC LNG MPLX O PSA TLT SCHX VCIT AMP HMC WCN CPRT D XYZ VRT NDAQ FICO EW TAK DFS HOOD MSCI FIS CVNA DHI TCOM KMB KR KDP LHX HWM PWR FAST VLO OXY BKR FANG HES VST CTVA XLF SCHF F PEG CCI DDOG GLW GRMN RMD PRU SLF AME FERG EXC CBRE GOLD VT IWB" +
  " VCSH CTSH EA ARGX VRSK YUM GIS XEL DIA XLV JEPI IXUS MUB SGOV SYY RBLX MCHP IT VEEV HUM IDXX A IQV LULU LVS LEN HSY KHC STZ DAL TRGP ED VMC IEF XLE VNQ SCHG SPYG HPQ HIG ACGL WAB DD IAU BSV VTEB BIL BIDU MTB WTW RJF EFX ABEV HEI ODFL HEI.A VICI EXR MLM NET ZS HUBS ON WIT ANSS MPWR TTD TTWO LYV RDDT CAH CNC DXCM STT BRO OWL TW QSR EBAY TSCO EL ROK XYL UAL EQT TPL WEC IRM AVB NUE DOW CCJ LQD VBR VGIT DGRO KEYS FITB BR K PPG LPLA FCNCA AWK VTR EQR GOVT HPE MTD NTAP GDDY SMCI CDW STM FTV WBD BNTX PHG SYF IBKR GPN CCL STLA DECK PHM LI ADM CHD DOV HAL DVN CHK DTE PPL SBAC LYB NTR WRK SHY SMH JEPQ TQQQ TYL HBAN WRB MKL CPAY SPYV STE FE AEE ZM STX WDC TDY CHKP IOT UI PINS NTRA LH WAT NTRS RF CINF TROW AFRM CBOE DRI EXPE NVR EME HUBB RBA ES CNP ATO INVH TECK MDY XLC SPDW BIV VGSH VGK PTC PODD ZBH LDOS TOST GRAB BIIB DGX TEVA RPRX CFG WSM TSN MKC LII CTRA FSLR COG CMS NRG ARE WY STLD IP PKG KGC AU IFF DVY XLI XLY FBTC ACWI GBTC SDY SSNC KEY MDB TER VRSN NTNX PSTG CYBR GEN NLOK SNAP UTHR WST PFG CG TPG DKNG ULTA XPEV YUMC DG LUV WSO NI ESS EEM XLU VBK OKTA TWLO DOCU ZBRA TRMB OMC FOXA ZG MOH THC TRU CRBG RYAN BIP RL BURL BBY DKS TPR USFD HRL CLX KOF J SNA CW MAA BALL HYG FNDX VOE SCHA USFR AZPN JBL DT NWSA FDS FNF APTV CASY BF.B EXPD CSL PNR LNT SUI XLP FFIV FLEX BSY DUOL ENTG ILMN BAX HOLX COO DPZ ONON DLTR CNH MAS CHRW XPO MRO WES EVRG KIM RS CF AVY RPM TIP VOT IWP EMB GDX EWJ SWKS AKA" +
  "M COHR BAH LOGI INCY CHWY EWBC EQH EG ARCC RIVN BLDR TXT GGG ACM JBHT DOC UDR AMCR SLV SOXX MOAT PFF JKHY MNDY ROKU WWE EDR NBIX EXAS ICLR ITCI INSM SWAV SMMT GMAB SNN UNM RGA JEF HLI MORN H BROS PFGC BJ IEX ITT FTAI PAA FTI AGR GLPI AMH ELS REG LAMR LINE WPC WLK JHX IWS JNPR PAYC MANH CLS LBRDK MRNA RVTY UHS EHC SOFI ALLY RNR TXRH TOL MGA POOL TAP CAG NDSN CLH UHAL PR CPT BXP HST JLL NOBL CIEN EPAM PCOR NVT BMRN GMED ALGN DVA VTRS CTLT MEDP TECH FHN BEN GL EVR SF AFG AIZ KNSL PAG MGM SCI ACI SFM CPB SJM BG COKE PPC MTZ SWK LECO BLD ARMK DRS BWXT CNM OVV OHI NLY CCK EMN SQM IWN IWO SCHM SCHP SCHO SOXL IGV HDV CACI PCTY DAY DOCS NICE AUR IPG EXEL TEM QGEN PEN ATR SEIC NCLH SKX BIRK WYNN TPX LKQ NIO HAS MMYT AOS AIT CR TTEK APG RBC ASTS AR DTM WTRG TLN PNW CUBE REXR CRS ALB PAAS MP SPEM SCHE VGLT INDA U ESTC ALTR WIX ONTO KVYO DSGX MTSI NYT FYBR IONS HIMS MASI WBA WAL WBS SSB PNFP ORI PRI WING CAVA GPS LAD INGR CELH BRBR PRMW RKLB PSN WCC ALSN MLI RRC BE VNOM OGE AES BEP FRT EGP AGNC X ATI MOS IJK EZU QRVO ENPH KD G CFLT GTLB PEGA APPF DBX LSCC IONQ CVLT PARA MTCH SIRI LUMN SATS HALO CRL CHE ENSG HSIC CORT MDGL ROIV REVMED HQY BFAM BIO VRNA ZION CMA CFR IVZ MKTX AXS FOUR ONB UMBF CBSH WTFC HLNE KMX PLNT LEVI LNW LW FLR AAL ALK SAIA GNRC TTC AVAV HII GTLS WTS DCI APA SWN NXT DINO HESM SUN VNO BRX NNN ADC EXP SUM AXTA AA GPK BERY XLRE ARKK IJJ SCHZ JNK BKLN FLOT PAVE CIBR FDN QYLD " +
  "EWT PATH S MKSI AMKR CCCS NVMI JAZZ LEGN SNV PB VOYA JXN BOKF RLI STEP WH LCID AN CHDN MHK BWA FIVE OLLI SRAD AGCO OSK DY AWI KNX FLS VMI LSTAR BECN ESAB MIDD INFA MTDR CHRD AM UGI STAG FR STWD CE ICL LOUP UFPI TREX AZEK IBB VCLT XBI KWEB LYFT VRNS ARW NOVT RMBS VERX SPSC NEWR GH BRKR LNTH AXSM BPMC CYTK NUVL ELAN CRVL VLY LNC WEX FAF UPST SLM OMF CACC FNB GBCI HOMB COLB VIRT ACIW THG JHG MTG ESNT BEPC OBDC BXSL EAT CHH VFC URBN ETSY W GPI CZR BYD WHR GNTX LTH MAT DDS MTN ELF POST DAR STRL MOG.A KTOS KEX AL SITE FSS MSA CSWI ZWS BMI CGNX RHI FCN ENLC IDA NFG RHP TRNO COLD EPRT SRC RITM CMC FMC NEU GRA LTHM KNF XLB ETHA BLV SRLN QLD FXI MCHI VPL LITE SAIC QLYS BILL SQSP ALGM CRUS WK QTWO CCMP VNT NXST USM ALKS KRYS TGTX INSP PCVX OPCH LHCG NYCB UBSI FFIN OZK SNEX LAZ PJT MC PIPR BGC FCFS SIGI BWIN AMG RDN ACT MAIN FSK SHAK THO CROX IBP LEA BOOT ABG VVV LOPE LRN LANC LSTR MSM MATX GATX TRTN IESC ROAD MOD ACA JBT ITRI LFUS HXL NOV CHX WFRD MGY NE POR SWX NJR ORA CUZ PECO CTRE AHR CLF SEE SON HL SLGN BCC TKR SCHR SPXL SSO IHI GDXJ ARKB EWZ EWY BOX TENB FROG ZI AVT SANM PLXS SLAB SITM CARG BRZE KNBE INTA FRSH CAMT AEIS OSIS ESE MSGS GSAT TDS IAC DJT CRSP VKTX OSCR PRGO RARE IRTC NARI PTCT ACAD RYTM ZLAB PBH TMDX RDNT ITGR EEFT STNE ASB IBOC TCBI ABCB EBC FULT GBDC AX TFSL NNI KMPR PLMR VCTR AGO AEL CNO BC PVH ANF KBH RH GOLF SIX FUN JWN M COLM KTB HGV RUSHB ATGE COTY FRPT FLO CALM S" +
  "AFM FIZZ IPAR SPR PRIM GVA EXPO DORM BCO GMS RUSHA FELE MWA BDC NPO KAI KFY TNET CBZ CIVI MUR CRC CNX CRK LB SR BKH ALE OGS SLG COMP HHH KRC SKT MAC SBRA IRT CBT SMG USLM RYN SJNK UPRO SKYY ETHE BITB DIVO PGX VNQI REET AI DXC RNG ASAN FORM ACLS POWI NCNO GLOB MGNI DV CNXC PRFT YOU ALRM BLKB ENV AGYS CALX IPGP CNK IRDM TGNA DISH CCOI JW.A RUM BEAM XRAY PDCO OGN PRVA ACHC SEM AMED APLS FOLD ARWR DNLI AXNX LIVN BHVN IMVT XENE SRRK CRNX ICUI PRCT CERT VCYT SGRY ALHC NEOG AKRO LMND WU DLO FIBK CATY HTLF PACW AUB BOH CBU CVBF FBP FHB INDB UCB WSFS ENVA BFH GSHD FHI NMIH GNW BHF HTGC HOG PII AEO PENN MTH TPH GT HIBB BATRA CPRI SIG PTON SEAS BKE UAA YETI SG CAKE VAC TNL STAY CAR DRVN BATRK RSI IGT LAUR JJSF SMPL TEX HEES POWL PAYO UNF MRCY VSEC TDW ZIM PATK VC ABM RXO ATS CXT VSE ASGN NSP SM NOG RUN GPOR USAC ARLP BSM PBF RIG VAL HP PTEN LBRT OII NWE MGEE OTTR AVA CWT AWR CPK MPW HIW PK APLE CWK OUT CDP DEI FCPT AKR NHI NSA BNL BXMT HUN OLN UEC LEU AVNT KWR GEF MDU PCH HCC CEIX EDV SQQQ KRE IYR URA BOTZ SPHD XYLD EWG EWU EWC SEDG VIAV EXTR VSH TTMI UCTT SYNA RGTI BB LZ YELP CRTO DBD NCR NCRV PRGS RAMP NABL CXM APPN SPNS DIOD BRKS QUBT SOUN KLIC VECO TRIP ZD LGF.A SRPT NTLA RXRX TXG NVCR CLOV OMCL VERA SUPN HRMY DYN IDYA AMPH NUVA ATEC CNMD UFPT LMAT NEO ADUS NHC PGNY GDRX AZTA LFST ROOT LC MQ PAGS BANR LKFN NBTB PPBI RNST SFNC SBCF TOWN TRMK WAFD FRME PFS EFSC NWBI FBNC EVTC SKWD WT TR" +
  "UP NWLI PSEC TSLX WEN HBI VSTO MODG SHOO WWW FL KSS CRI ELY CWH SAH BOWL GENI MCRI STRA PRDO SAM UNFI TR FDP VITL CHEF JBLU WERN ATKR DNOW ARCB HUBG LCII ADNT REVG ALG KMT HNI TRN GBX EPAC SXI CSTM AIR LUNR PL MAN UPWK HURN ICFI PLUG CVI CPE SDRL HE SJW NWN OPEN EXPI ESRT GTY ROIC DRH SHO XHR PEB IIPR ABR CENX IOSP ASH HWKN AMR BTU ARCH WOR XHB XOP ITB ICLN COPX HACK ARKW BITO EWA YEXT FSLY RPD SONO BHE COUR CHGG CARS PUBM IAS VNET XRX IMMR INSE GDYN TASK IBEX UIS THRY ZUO AMPL SEMR OLO SPT EVBG SUMO JAMF ATEN CMBM DGII INFN HLIT CASA COMM NTGR VSAT GILT KVHI CEVA IMOS PLAB AOSL LASR ICHR ARQQ BBAI CXAI VERI LAZR OUST INVZ MVIS KOPN EMAN HIMX COHU ASYS AXTI WOLF NVEC SGH FARO MLAB FUBO IMAX BMBL GTN SSP ATEX CNSL SHEN ATNI IHRT AUD CMLS SBGI GCI LEE SCHL DJCO STGW CCO BOC QNST ANGI EVER CURI AMCX AMC MCS PACB TNDM CYH TDOC SNDX KURA COLL EMBC SRDX RXST STAA OM BLFS SILK SDGR CDNA MYGN FLGT PNTG USPH EVH ACCD RAD PETQ WOOF HCAT PHR AMWL TALK AORT KIDS VIR SAGE ALLO EDIT VERV PRME SANA CGEM ARVN OLMA ERAS NAVI HOPE STBA CFB CUBI NBHC SASR QCRH BUSE VBTX DCOM MSBI STEL BHLB KRNY DFIN PRAA ECPG ATLC GDOT PSFE RPAY HCI CRD.B TREE ARTV BSIG MBI AMBC CCRN HRTG UVE UFCS DGICA SAFT EIG AMSF PRA JRVR NMFC OCSL CSWC TPVG SLRC PZZA JACK LEG MOV XPOF FNKO CATO CHS EXPR GES OXM GIII GOOS SWBI RGR AOUT JOUT MCFT MBUU HZO ONEW LAZY CRMT VRM REAL POSH FTCH QRTEA OSTK GRPN SKIN NUS HLF USNA MED " +
  "PTLO FWRG BJRI CBRL DENN LOCO NDLS RRGB PLAY PLYA LIND TZOO DESP SABR HTZ MNRO GAMB LTRY ACEL GDEN FLL EVRI SONDER RICK NATH ARKR STKS UTI APEI CVGW UTZ JBSS DOLE THS HAIN SENEA LWAY STKL BGS KLG NAPA WEST SPTN ANDE SPCE SAVE GNK NVEE ORN MRTN HTLD SMP AXL THRM SHYF BLBD WNC LNN TWI MTW ASTE HY MLKN SCS FWRD TITN THR TNC CIR CTS ROG HLIO DXPE NPK LAKE PRLB DDD SSYS MKFG XMTR FIP OFLX ATRO DCO TGI CVU NPKI UAVS RDW SPIR BKSY HSII KELYA KFRC FVRR ZIP HQI BBSI CRAI FORR ARRY DK PARR VTLE GEL NGL GLP KRP DMLP DO CLB UTL MSEX YORW ARTNA GWRS RGCO RDFN UNIT PSTL JBGS PGRE CBL SVC INN CHCT GMRE LTC SAFE ALEX GNL ONL UMH NXRT VRE CSR AAT CIM TWO MFA PMT ARR DX RC LADR SCL UAN MYE HAYN SCHN ZEUS RYI TMST IIIN NX USO UNG DBC ZROZ TMF SH PSQ VXX UVXY SVXY XRT XME XHE KBE IYT TAN LIT SIL ROBO ARKG ARKF JETS BETZ MJ RYLD B E I L R Y Z AB AC AE AG AP AQ AT AY BH BL BP BT BV BW BY CC CJ CM CO CS CX CY DB DF DL DQ DS EB EC EE EQ EV FB FC FF FG FN FT GF GG GV HA HF HI HK HR HT HX IO IQ IR IX JE JG JP JT KB KE KF KL KN KT KW LE LL LM LN LX MB MD MG MN MT MX NC NG NH NK NL NM NP NR NS OC OI OR PE PI PS PT PW PY QD RA RE RM RP SA SB SC SD SN SP SQ ST SU TA TC TG TI TK TS TU TV TX TY UA UE UG UN VG WB WD WP XT YI YY ZF ZN AAC AAN AAP AAU ABC ACB ACC ACH ACP ACU ACV ACY ADS ADT ADX AEB AED AEF AEG AEH AER AEY AFB AFC AFH AFI AFT AGD AGE AGI AGM AGN AGS AGX AHC AHH AHL AHT AIA AIC AIF AIN AIQ AIV AIW" +
  " AIY AJX AKG AKP AKS ALO ALT ALV ALX AMN AMS AMX ANH ANY AOD APC APF APH APM APT APU APY AQB AQN ARA ARC ARD ARI ARL ASA ASC ASG ASM ASR AST ASV ASX ATH ATU ATV AUG AUO AUY AVD AVH AVK AVP AVX AWF AWP AWX AXE AXO AXR AXU AYI AYR AYX AZZ BAF BAK BAP BAS BBC BBD BBF BBH BBK BBL BBN BBP BBT BBU BBW BBX BCE BCH BCS BCV BCX BDJ BDL BDN BDR BEL BFC BFK BFL BFO BFR BFS BFY BFZ BGB BGG BGH BGI BGR BGT BGX BGY BHB BHC BHK BHP BHR BHV BIB BID BIF BIG BIS BIT BKD BKI BKJ BKK BKN BKS BKT BKU BLE BLL BLW BLX BMA BME BMS BNY BOE BPI BPL BPR BPT BPY BQH BRC BRG BRN BRS BRT BRY BSA BSD BSE BSL BST BTA BTE BTG BTI BTN BTO BTT BTX BTZ BUI BVN BWB BWG BXC BXE BXG BXS BYM BZH BZM CAC CAE CAF CAI CAJ CAL CAW CBB CBD CBH CBK CBM CBO CBS CBX CCA CCB CCC CCD CCF CCH CCM CCR CCS CCU CCZ CDC CDE CDK CDL CDR CEA CEE CEI CEL CEM CEN CEO CET CEV CEY CEZ CFA CFO CFX CGA CGC CGO CHA CHI CHL CHN CHT CHU CHW CHY CIA CIB CIC CID CIF CIG CII CIK CIL CIO CIT CIX CIZ CKH CKX CLD CLI CLM CLR CLW CMD CMO CMP CMT CMU CNA CNF CNQ CNS COE COT CPA CPF CPG CPL CPS CQP CRF CRH CRR CRT CRY CSA CSB CSF CSQ CSS CSU CSV CTB CTG CTK CTL CTO CTR CTT CTV CTY CTZ CUB CUE CUI CUK CUO CUR CVA CVE CVM CVR CVV CXE CXH CXO CXP CXW CYD CZZ DAC DAN DAX DBL DCF DCP DDE DDF DDT DEA DEX DHF DHT DHX DHY DIN DIT DKL DKT DLA DLB DLX DMB DMF DMO DNI DNN DNP DNR DOX DPG DPW DRD DRE DRQ DSE DSL DSM DSS DSU DSW DSX DTF DTJ DTQ DTV DTW DTY DUC DVD" +
  " DXB DXF DXR EAB EAD EAE EAF EAI EBF EBR EBS ECA ECC ECF ECR ECT EDD EDF EDI EDN EDU EEA EEI EEX EFC EFF EFL EFR EFT EGF EGI EGO EGY EHI EHT EIM EIV EIX ELC ELJ ELP ELU EMD EMF EML EMO EMP EMX ENB ENG ENJ ENO ENR ENS ENT ENX ENZ EOD EOI EOS EOT EPC EPE EPM EPR EQC EQM EQS ERA ERC ERF ERH ERI ERJ ESG ESI ESL ESP ESQ ESV ETB ETG ETH ETJ ETM ETO ETR ETV ETW ETX ETY EVA EVC EVF EVG EVI EVJ EVK EVM EVN EVT EVV EVY EXD EXG EXK EYE EZT FAB FAD FAM FAT FAX FBC FBK FBM FBZ FCA FCF FCO FCT FDC FDT FEI FEM FEN FEO FEP FET FEX FFA FFG FGB FGM FGP FHK FID FIF FII FIT FIV FIX FJP FKO FKU FLC FLF FLN FLT FLY FMB FMK FMN FMO FMS FMX FMY FND FNK FNV FNX FNY FOE FOF FOR FOX FPA FPH FPI FPL FRA FRC FRD FRO FSB FSD FSI FSM FSP FSV FSZ FTA FTC FTD FTF FTK FTR FTS FUL FUV FVE FWP FYC FYT FYX GAB GAM GBL GBR GBT GCO GCP GCV GDI GDL GDO GDP GDS GDV GEC GEO GER GFF GFI GFN GFY GGB GGM GGN GGO GGT GGZ GHC GHG GHL GHM GHY GIB GIG GIL GIM GJH GJO GJP GJR GJS GJT GJV GLG GLO GLQ GLT GLU GLV GME GMO GMZ GNC GNE GNT GOF GOL GPC GPL GPM GPP GPX GRC GRF GRX GSB GSH GSL GSM GSS GSV GTE GTS GTT GTX GUT GVP GWB GWR GYB GYC GZT HAE HBB HBK HBM HBP HCM HCP HDS HEB HEP HEQ HFC HGH HHC HHS HIE HIL HIO HIX HJV HLG HLX HMG HMI HMN HMY HNP HNW HOS HOV HPF HPJ HPP HPR HPT HQH HQL HRB HRC HRI HRS HSC HTA HTD HTH HTY HUD HVT HWC HYB HYI HYT HZN IAE IAF IAG IBA IBO ICD IDE IDN IDT IEA IEC IEI IEP IFN IGA IGD IGF IGI IGR IHC" +
  " IHD IHG IHT IID IIF III IIM IIN IJT IMH IMI IMO IMV INB INF ING INO INS INT IOR IPI IQI IRL IRR IRS ISD ISF ISG ISR ITG ITI ITP IUS IVC IVH IVR JAG JAX JBK JBN JBR JCE JCO JCP JCS JDD JEC JEQ JFR JGH JHB JHD JHI JHS JHY JKI JKS JLS JMF JMM JMP JMT JMU JOB JOE JOF JQC JRI JRO JRS JSD JSM JTA JTD JVA KAR KBR KEG KEM KEN KEP KFS KIN KIO KIQ KMF KNL KOD KOP KOS KRA KRG KRO KSM KSU KTF KTH KTN KTP KYN KZR LAC LBC LBY LCI LDL LEO LFC LGI LGL LHC LLL LMB LND LOB LOR LOV LPG LPI LPL LPT LPX LSI LTM LTS LUB LXP LXU LYG LYL LZB MAG MAV MBB MBT MCA MCB MCC MCF MCI MCN MCR MCV MCX MCY MDC MDP MDR MEI MEN MFD MFG MFL MFM MFO MFT MFV MGF MGI MGP MGU MHD MHE MHF MHH MHI MHN MHO MIC MIE MIK MIN MIY MLP MLR MMD MMI MMP MMS MMT MMU MNE MNI MNK MNP MNR MOC MOR MPA MPB MPO MPV MPX MQT MQY MRC MRT MSB MSC MSD MSF MSG MSL MSN MTC MTL MTP MTR MTT MTX MUA MUC MUE MUH MUI MUJ MUS MUX MVC MVF MVO MVT MXC MXE MXF MXL MYC MYD MYF MYI MYJ MYL MYN MYO MZA NAC NAD NAK NAN NAO NAT NAV NAZ NBB NBH NBL NBN NBO NBR NBW NBY NCA NCB NCI NCS NCV NCZ NDP NEA NEN NEP NES NEV NEW NFC NFE NFJ NFX NGD NGG NGS NHA NHF NHS NID NIE NIM NIQ NIU NJV NKG NKX NLS NMI NML NMM NMR NMS NMT NMY NMZ NNC NNY NOA NOK NOM NPN NPV NQP NRC NRE NRK NRO NRP NRT NRZ NSL NSS NSU NTB NTC NTG NTN NTP NTX NTZ NUM NUO NUV NUW NVG NWL NWS NXC NXE NXJ NXN NXP NXQ NXR NYV NZF OAK OAS OBE OCC OCN OCX ODC ODP ODT OEC OFC OFG OFS OIA OIS OLD OLP OMI" +
  " OMN OMP ONE OPB OPI OPK OPP OPY ORC ORG ORM OSB OSG OSN OSS OZM PAC PAI PAM PAR PBA PBB PBC PBI PBR PBT PBY PCB PCF PCG PCI PCK PCM PCN PCQ PDI PDM PDP PDS PDT PED PEI PEO PER PES PEY PEZ PFH PFI PFL PFM PFN PGC PGJ PGP PGZ PHD PHI PHK PHO PHT PHX PID PIE PIH PIM PIO PIR PIY PIZ PJC PJH PKE PKI PKO PKW PKX PLG PLL PLM PLT PLW PLX PMD PME PMF PML PMM PMO PMX PNF PNI PNM POL PPH PPR PPT PPX PQG PRH PRK PRN PRO PRS PRT PSB PSC PSL PSO PTE PTF PTH PTI PTN PTR PTX PTY PUB PUI PUK PVG PVL PXD PXI PXS PYN PYS PYT PYX PYZ PZC PZG PZN QAT QEP QES QHC QLC QTS QTT RBB RBS RBZ RCA RCG RCI RCM RCP RCS RDC RDI RDY REI REN RES REV REX RFI RFL RFP RGS RGT RHE RHT RIF RIO RIV RLH RLJ RLM RMI RMR RMT RNN ROL ROX RPT RQI RRD RRR RST RTN RTW RVI RVP RVT RWT RXN RYB RZA RZB SAB SAF SAL SAN SAR SBH SBI SBR SBS SBT SCA SCD SCM SCX SCZ SDG SDI SDR SDT SEB SES SFB SFE SFL SFS SGA SGB SGC SGU SHG SHI SHV SIC SID SIF SIM SJI SJR SJT SKM SKY SLP SLS SMI SMM SND SNE SNH SNP SNR SNX SOI SOL SOR SPA SPB SPE SPH SPI SPN SRF SRG SRI SRT SRV SSD SSI SSL SSW SSY STC STG STI STK STL STN SUP SUZ SVA SVM SVT SWI SWJ SWM SWP SWZ SXC SXE SXT SYN SYX SZC TAC TAL TAT TBB TBC TBI TBK TCF TCI TCO TCP TCS TCX TDA TDC TDE TDF TDI TDJ TEF TEI TEL TEN TEO TFX TGA TGB TGC TGE TGH TGP TGS THM THQ THW TIF TIK TIS TKC TLC TLF TLI TLK TLP TME TMK TMP TMQ TNK TNP TOO TOT TPB TPC TPZ TRC TRI TRK TRP TRQ TRS TRT TRX TSC TSE TSG TSI" +
  " TSQ TSS TST TSU TTI TTM TTP TTS TUP TUR TVC TVE TWN TYG UAE UBA UBP UBX UFI UFS UGP UHT ULH UMC UNB UPL UQM URG USA USG USX UTF UTG UTX UUU UVV UWN UZA UZB UZC VAM VAR VBF VCF VCV VEC VER VET VFL VGI VGM VGR VGZ VHC VHI VIA VIV VKI VKQ VLT VMM VMO VMW VNE VOC VOD VPG VPV VRA VRS VSI VSM VTA VTC VTL VTN VVI VVR WBC WBK WBT WCG WDR WEA WEI WFT WGO WGP WHD WHF WHG WIA WIN WIW WLH WLL WMC WMK WMS WNS WOW WPG WPM WPP WPX WRE WRI WRN WSC WSR WTI WTM WTR WTT WVE WWD WWR WYY XAN XEC XIN XOG XON XPL XRF XYF YIN YPF YRD YVR ZBK ZEN ZIV ZNH ZOM ZTO ZTR AABA AAMC AAME AAOI AAON AAWW AAXJ AAXN ABDC ABEO ABIL ABIO ABMD ABTX ABUS ACBI ACCO ACER ACET ACHN ACHV ACIA ACIU ACMR ACNB ACOR ACRE ACRS ACRX ACST ACTG ACWX ADAP ADES ADIL ADMA ADMP ADMS ADOM ADRA ADRD ADRE ADRO ADRU ADSK ADSW ADTN ADVM ADXS AEGN AEHR AEMD AERI AETI AEYE AEZS AFGE AFGH AFIN AFMD AGEN AGFS AGIO AGLE AGMH AGND AGRO AGRX AGTC AGZD AHPI AIHS AIMC AIMT AINC AINV AIPT AIRG AIRI AIRR AIRT AIZP AJRD AJXA AKAO AKBA AKCA AKER AKRX AKTS AKTX ALBO ALCO ALDR ALDX ALEC ALGR ALGT ALIM ALJJ ALLE ALLK ALLT ALNA ALOT ALPN ALQA ALRN ALSK ALTM ALTY ALXN ALYA AMAG AMAL AMBA AMBO AMBR AMCA AMCN AMEH AMGP AMID AMNB AMOT AMOV AMPE AMRB AMRC AMRH AMRK AMRN AMRS AMRX AMSC AMTB AMTD AMTX AMWD ANAB ANAT ANDX ANFI ANGO ANIK ANIP ANIX ANTM AOBC APAM APDN APEN APHA APHB APOG APOP APPS APRN APTO APTX APVO APWC APYX AQMS AQNA AQST AQUA AQXP ARAV ARAY A" +
  "RCE ARCI ARCO ARCT ARCW ARDC ARDS ARDX AREX ARGD ARGO ARLO ARNA ARNC AROC AROW ARPO ARQL ARRS ARTW ARTX ASET ASFI ASIX ASLN ASMB ASNA ASND ASNS ASPN ASPS ASPU ASRT ASRV ASTC ASUR ATAI ATAX ATHM ATHN ATHX ATIS ATLO ATNM ATNX ATOM ATOS ATRA ATRC ATRI ATRS ATSG ATTO ATTU ATUS ATVI ATXI AUBN AUDC AUMN AUPH AUTL AUTO AVAL AVCO AVDL AVEO AVGR AVID AVLR AVNS AVNW AVRO AVXL AVYA AWRE AWSM AXAS AXDX AXGN AYTU AZRE AZRX AZUL BABY BANC BAND BANF BANX BASI BBBY BBCP BBDC BBDO BBGI BBVA BCBP BCEI BCLI BCML BCNA BCOM BCOR BCOV BCOW BCPC BCRH BCRX BCSF BCTF BDGE BDSI BDXA BEAT BFIN BFIT BFRA BFST BGCP BGFV BGIO BGNE BGRN BGSF BHBK BHGE BHTG BICK BILI BIMI BIOC BIOL BIOS BIQI BITA BKCC BKCH BKEP BKSC BKTI BKYI BLCM BLCN BLDP BLIN BLMN BLMT BLNK BLPH BLRX BLUE BMCH BMLP BMRA BMRC BMTC BNCL BNDW BNED BNFT BNGO BNSO BNTC BOCH BOLD BOMN BOOM BORN BOSC BOTJ BOXL BPFH BPMP BPMX BPOP BPRN BPTH BREW BRFS BRID BRKL BRQS BRSS BSAC BSBR BSET BSGM BSMX BSQR BSRR BSTC BSTI BSVN BTAI BTEC BURG BVSN BVXV BWEN BWFG BWMC BXMX BYFC BYSI BZUN CAAP CAAS CABO CACG CADC CADE CALA CAMP CANF CANG CAPL CAPR CARA CARB CARO CART CARV CARZ CASH CASI CASM CASS CATB CATC CATH CATM CATS CBAN CBAT CBAY CBFV CBIO CBLI CBLK CBMB CBMG CBNK CBPO CBPX CBTX CCBG CCCL CCEP CCIH CCLP CCNE CCNI CCRC CCXI CDAY CDEV CDLX CDMO CDOR CDTX CDXC CDXS CDZI CECE CECO CELC CELG CELP CEMI CENT CEPU CEQP CERC CERN CERS CETV CETX CFBI CFBK CFFI C" +
  "FFN CFMS CFRX CFXA CGBD CGEN CGIX CHAP CHCI CHCO CHEK CHFC CHFS CHIC CHKE CHKR CHMA CHMG CHMI CHNA CHNR CHRA CHRS CHSP CHUY CIDM CIFS CIGI CINR CISN CIVB CIZN CJJD CKPT CLAR CLBK CLBS CLCT CLDC CLDR CLDT CLDX CLFD CLGN CLGX CLIR CLLS CLMT CLNC CLNE CLNY CLPR CLPS CLRB CLRG CLRO CLSD CLSN CLUB CLVS CLWT CLXT CMCL CMCM CMCO CMCT CMFN CMPR CMRE CMRX CMSA CMSC CMTA CMTL CNAC CNAT CNCE CNCR CNDT CNET CNFR CNHI CNNE CNOB CNST CNTF CNTY CNXM CNXN COCP CODA CODI CODX COHN COMT CONE CONN COOP CORE CORR CORV COUP COWN CPAC CPAH CPHC CPHI CPIX CPLG CPLP CPRX CPSH CPSI CPSS CPST CPTA CRAY CRBP CRCM CREE CREG CREX CRHM CRIS CRMD CRNT CRON CRVS CRWS CRZO CSBR CSFL CSGP CSGS CSII CSIQ CSLT CSML CSOD CSPI CSSE CSTE CSTR CTAA CTBB CTBI CTDD CTEK CTHR CTIB CTIC CTMX CTRC CTRL CTRN CTRP CTRV CTSO CTWS CTXR CTXS CUBA CULP CURO CUTR CVCO CVCY CVEO CVET CVGI CVIA CVLY CVRS CVTI CWBC CWBR CWCO CWEN CWST CXDC CXSE CYAD CYAN CYBE CYCC CYOU CYRN CYRX CYTR CYTX CZFC CZNC CZWI DAIO DAKT DARE DATA DAVA DAVE DBVT DCAR DCIX DCPH DCUD DDBI DELT DERM DEST DFBH DFFN DFNL DFRG DFVL DFVS DGLD DGLY DGRE DGRS DGRW DGSE DHIL DHXM DIAX DINT DLBS DLHC DLNG DLPH DLPN DLTH DMAC DMPI DMRC DNBF DNJR DNKN DOGZ DOMO DOOO DOOR DOVA DPLO DRAD DRIO DRIV DRNA DRRX DRUA DRYS DSKE DSLV DSPG DSWL DTEA DTSS DTUL DTUS DTYL DTYS DUKB DUKH DUSA DVAX DVCR DWAQ DWAS DWAT DWCR DWDP DWIN DWLD DWLV DWSN DWTR DXGE DXJS DXLG DXYN DYNC DYNT D" +
  "YSL DZSI EARN EARS EAST EBIX EBIZ EBMT EBSB EBTC ECCA ECCB ECCX ECCY ECHO ECOL ECOM ECOR EDAP EDBI EDGE EDNT EDRY EDUC EEMA EFAS EFBI EFII EFOI EGAN EGBN EGHT EGIF EGLE EGOV EGRX EHIC EHTH EIDX EIGI EIGR EKSO ELGX ELLI ELLO ELMD ELOX ELSE ELTK ELVT EMCB EMCF EMCG EMCI EMES EMIF EMKR EMMS EMXC ENBA ENBL ENDP ENFC ENIA ENIC ENOB ENSV ENTA ENTX ENZL EOLS EPAY EPIX EPZM EQBK EQNR EQRR ERIC ERIE ERII EROS ERYP ESBK ESCA ESEA ESGD ESGE ESGG ESGR ESGU ESLT ESNC ESPR ESSA ESTA ESTE ESTR ESXB ETFC ETON ETRN ETTX EUFN EURN EVBN EVFM EVGN EVLO EVLV EVOK EVOL EVOP EWZS EXFO EXLS EXTN EYEG EYEN EYES EYPT EZPW FAAR FALN FAMI FANH FARM FATE FBHS FBIO FBIZ FBMS FBSS FCAL FCAN FCAP FCAU FCBC FCBP FCCO FCCY FCEF FCEL FCSC FCVT FDBC FDEF FDEU FDIV FDNI FDTS FDUS FEDU FEIM FELP FEMB FEMS FENC FENG FEUZ FEYE FFBC FFBW FFHL FFIC FFNW FFWM FGBI FGEN FINX FISI FISV FIVN FIXD FIXX FLAG FLAT FLDM FLIC FLIR FLKS FLMN FLNT FLOW FLWS FLXN FLXS FMAO FMBH FMBI FMCI FMHI FMNB FNCB FNHC FNJN FNLC FNSR FNWB FOCS FOMX FONE FONR FORD FORK FOSL FOXF FPAY FPRX FPXE FPXI FRAC FRAN FRBA FRBK FRED FRGI FRPH FRSX FRTA FSBC FSBW FSCT FSFG FSNN FSTR FTAG FTCS FTDR FTEK FTEO FTFT FTGC FTHI FTLB FTNW FTRI FTSI FTSL FTSM FTSV FTXD FTXG FTXH FTXL FTXN FTXO FTXR FUNC FUND FUSB FVCB GABC GAIA GAIN GALT GARS GASS GBAB GBLI GCAP GCBC GECC GEMP GENC GENE GENY GEOS GERN GEVO GFED GGAL GHDX GIFI GIGM GKOS GLAD GLBS GLBZ GLDD GLDI G" +
  "LMD GLNG GLOG GLOP GLOW GLPG GLRE GLUU GLYC GMDA GMLP GMTA GNCA GNMA GNMK GNMX GNPX GNRX GNTY GNUS GOGL GOGO GOOD GOOG GORO GOSS GPIC GPJA GPMT GPRE GPRK GPRO GRAF GRAM GRBK GRFS GRID GRIF GRIN GRNQ GROW GRSH GRTS GRUB GRVY GSAH GSBC GSBD GSIT GSKY GSUM GSVC GTES GTHX GTIM GTXI GTYH GULF GURE GWGH GWPH GWRE GYRO HABT HAFC HAIR HALL HARP HASI HBCP HBIO HBMD HBNC HCAP HCCH HCCI HCFT HCHC HCKT HCLP HCSG HCXY HCXZ HDSN HEAR HEBT HELE HEWG HEXO HFBC HFBL HFFG HFRO HFWA HGSH HIFR HIFS HIHO HIIQ HIVE HJLI HLTH HMHC HMLP HMNF HMNY HMST HMSY HMTA HMTV HNDL HNGR HNNA HNRG HOFT HOLI HOME HONE HOTH HROW HRTX HRZN HSDT HSGX HSKA HSON HSTM HTBI HTBK HTBX HTFA HTGM HTHT HURC HUSA HUYA HVBC HWBK HWCC HYGS HYLS HYND HYRE HYXE HYZD HZNP IART IBCP IBIO IBKC IBTX IBUY ICAD ICBK ICCC ICCH ICLK ICON ICPT IDCC IDEX IDLB IDRA IDSA IDSY IDTI IDXG IEUS IFEU IFFT IFGL IFMK IFRX IGIB IGLD IGOV IGSB IHIT IHTA IIIV IIJI IIVI IKNX ILPT IMAC IMDZ IMGN IMMP IMMU IMRN IMTE IMXI INAP INBK"
).split(" ").filter(Boolean);

const UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const TIME_BUDGET_MS = 45_000;   // stop before the platform kills us
const CONCURRENCY    = 12;       // parallel fetches; gentle enough to avoid 429s
const DEFAULT_LIMIT  = 900;

async function fetchQuote(symbol: string) {
  const url = "https://query1.finance.yahoo.com/v8/finance/chart/" +
    encodeURIComponent(symbol) + "?range=1d&interval=1d";
  const res = await fetch(url, { headers: { "User-Agent": UA, "Accept": "application/json" } });
  if (!res.ok) return null;
  const json = await res.json();
  const meta = json?.chart?.result?.[0]?.meta;
  if (!meta || meta.regularMarketPrice == null) return null;
  const price = Number(meta.regularMarketPrice);
  const prev  = Number(meta.chartPreviousClose ?? meta.previousClose ?? price);
  const change = price - prev;
  return {
    symbol,
    name: meta.shortName || meta.longName || symbol,
    price,
    change,
    change_pct: prev ? (change / prev) * 100 : 0,
    prev_close: prev,
    updated_at: new Date().toISOString(),
  };
}

// Retry once on a miss — a single 429 shouldn't cost a ticker its price.
async function fetchQuoteRetry(symbol: string) {
  const first = await fetchQuote(symbol).catch(() => null);
  if (first) return first;
  await new Promise((r) => setTimeout(r, 350));
  return await fetchQuote(symbol).catch(() => null);
}

Deno.serve(async (req) => {
  const started = Date.now();
  try {
    const u = new URL(req.url);
    const mode   = u.searchParams.get("mode") || "stale";
    const limit  = Math.min(Number(u.searchParams.get("limit")) || DEFAULT_LIMIT, SYMBOLS.length);
    let   offset = Number(u.searchParams.get("offset")) || 0;

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );

    // Decide what this run should work on.
    let queue: string[];
    if (u.searchParams.has("offset")) {
      queue = SYMBOLS.slice(offset, offset + limit);
    } else {
      const { data: have } = await supabase
        .from("stock_prices").select("symbol, updated_at");
      const seen = new Map((have || []).map((r: any) => [r.symbol, r.updated_at]));
      const missing = SYMBOLS.filter((s) => !seen.has(s));
      if (mode === "missing") {
        queue = missing.slice(0, limit);
      } else {
        // anything we've never priced first, then the stalest rows
        const stale = SYMBOLS.filter((s) => seen.has(s))
          .sort((a, b) => new Date(seen.get(a) || 0).getTime() - new Date(seen.get(b) || 0).getTime());
        queue = missing.concat(stale).slice(0, limit);
      }
    }

    const rows: any[] = [];
    const failed: string[] = [];
    let i = 0;
    let ranOut = false;

    async function worker() {
      while (i < queue.length) {
        if (Date.now() - started > TIME_BUDGET_MS) { ranOut = true; return; }
        const sym = queue[i++];
        const q = await fetchQuoteRetry(sym);
        if (q) rows.push(q); else failed.push(sym);
      }
    }
    await Promise.all(Array.from({ length: CONCURRENCY }, worker));

    // Upsert in slices so one oversized payload can't fail the lot.
    let saved = 0;
    for (let k = 0; k < rows.length; k += 400) {
      const slice = rows.slice(k, k + 400);
      const { error } = await supabase.from("stock_prices").upsert(slice, { onConflict: "symbol" });
      if (!error) saved += slice.length;
    }

    const nextOffset = u.searchParams.has("offset")
      ? (offset + queue.length >= SYMBOLS.length ? 0 : offset + queue.length)
      : null;

    return new Response(JSON.stringify({
      ok: true,
      universe: SYMBOLS.length,
      attempted: queue.length,
      saved,
      failed: failed.length,
      failedSample: failed.slice(0, 20),
      timedOut: ranOut,
      nextOffset,
      seconds: Math.round((Date.now() - started) / 1000),
    }), { headers: { "Content-Type": "application/json" } });
  } catch (e) {
    return new Response(JSON.stringify({ ok: false, error: String(e) }), {
      status: 500, headers: { "Content-Type": "application/json" },
    });
  }
});
